version: '3'
services:
  api:
    image: node:14.17.2
    ports:
      - 3000:3000
    environment:
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=doggospass
      - PGDATABASE=doggos
      - COHORT=shaw
      - PGPORT=5432
    volumes:
      - type: bind
        source: ./mca-server
        target: /server
    working_dir: /server
    command: bash -c "npm install && npm run dev"
    depends_on:
      - db

  client:
    image: node:16.15.0
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./mca-client
        target: /client
    working_dir: /client
    command: bash -c "npm install && npm run dev"

  db:
    image: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=doggos
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=doggospass
volumes:
  dbdata:
